version: '3'

services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'wallet_manager'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'dbrootpassword'
    ports:
      - '3306:3306'

  web:
    build: .
    entrypoint: [ '/bin/bash', '/code/start.sh' ]
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
