# Generated by Django 5.0.6 on 2024-05-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
